#!/usr/bin/env bash
# installing and configuring HAproxy as loadbalancer
# that sneds traffic to web-01 and web-02 servers
# using th eroundrobin algo

# installation
sudo apt-get -y update
apt-get -y install haproxy=2.0.\*

config_ser =\
"
fronend my-frontend
        bind *:80
        mode http
        default_backend my-backend
backend my-backend
        balance roundrobin
        server 426816-web-01 35.168.3.19:80 check
        server 426816-web-02 34.224.94.62:80 check
"

echo "$config_ser" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

