#!/usr/bin/env bash
# print a string 10 times with a while loop
# +after the 9th interation print another

my_string="best school"
i=1
while [ "$i" -ne 11 ]; do
      echo "$my_string"
      if [ "$i" -eq 9 ]; then
      	 echo "Hi"
      fi
      i=$((i + 1))
done
